name: my_diary_app
description: A timeline diary app.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ðŸ‘‡ æ ¸å¿ƒä¾èµ– (æ–°å¢žäº†ä¸¤ä¸ª)
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.0      # ç”¨äºŽå¯¼å‡ºæ–‡ä»¶
  path_provider: ^2.1.1   # ç”¨äºŽç”Ÿæˆä¸´æ—¶æ–‡ä»¶

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  # ðŸ‘‡ æ³¨å†Œå›¾ç‰‡
  assets:
    - assets/images/

  # ðŸ‘‡ æ³¨å†Œä½ çš„å­—ä½“ (ç¡®ä¿æ–‡ä»¶åä¸º myfont.ttf ä¸”æ”¾åœ¨ assets/fonts/ ä¸‹)
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/myfont.ttf
        
# ðŸ‘‡ 1. å›¾æ ‡é…ç½®
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # é€‚é…å®‰å“ç³»ç»Ÿ

# ðŸ‘‡ 2. å¯åŠ¨å›¾é…ç½®
flutter_native_splash:
  color: "#FFFFFF" # å¯åŠ¨é¡µèƒŒæ™¯è‰² (ç™½è‰²)
  image: "assets/images/splash.png" # ä¸­é—´çš„ Logo å›¾
  android_12: 
    image: "assets/images/splash.png"
    color: "#FFFFFF"
  fullscreen: true