name: pdf_tool_pro
description: A powerful PDF tool app with Python backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
